# Generated by Django 3.0.4 on 2020-04-04 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Adress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('text', models.TextField()),
                ('ShowtimeFrom', models.DateTimeField()),
                ('Showtimeto', models.DateTimeField()),
                ('ShowtimeSeconds', models.IntegerField(default=0)),
                ('adress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Adress')),
            ],
        ),
    ]
